baseurl = 'https://dnac.cisco.com'
user = 'username'
password = 'password'
gmail_user = 'address@gmail.com'
gmail_password = 'password'
alert_destination = 'address@noc.com'
alert_title = 'DNAC - New Global Issue Alert'